### ISSUE TITLE
pkglistgen: IOError: Not a gzipped file (intermittent)

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#1415]
I see that quite often in the log:
```
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]: -> do_dump_solv for openSUSE:Leap:42.2:Update/non-oss
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]: Traceback (most recent call last):
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:   File "/usr/bin/osrt-pkglistgen", line 1358, in <module>
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:     sys.exit(app.main())
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:   File "/usr/lib/python2.7/site-packages/cmdln.py", line 261, in main
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:     return self.cmd(args)
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:   File "/usr/lib/python2.7/site-packages/cmdln.py", line 284, in cmd
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:     retval = self.onecmd(argv)
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:   File "/usr/lib/python2.7/site-packages/cmdln.py", line 422, in onecmd
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:     return self._dispatch_cmd(handler, argv)
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:   File "/usr/lib/python2.7/site-packages/cmdln.py", line 1123, in _dispatch_cmd
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:     return handler(argv[0], opts, *args)
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:   File "/usr/bin/osrt-pkglistgen", line 1037, in do_update_and_solve
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:     self.do_update_and_solve(subcmd, copy.deepcopy(opts))
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:   File "/usr/bin/osrt-pkglistgen", line 1056, in do_update_and_solve
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:     self.update_and_solve_target(apiurl, target_project, target_config, main_repo, opts, drop_list=True)
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:   File "/usr/bin/osrt-pkglistgen", line 1194, in update_and_solve_target
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:     apiurl, cache_dir_solv, target_project, family_last, family_include, opts)
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:   File "/usr/bin/osrt-pkglistgen", line 1276, in solv_cache_update
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:     names.append(self.do_dump_solv('dump_solv', opts, url))
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:   File "/usr/bin/osrt-pkglistgen", line 905, in do_dump_solv
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:     f.write(content.read())
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:   File "/usr/lib64/python2.7/gzip.py", line 261, in read
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:     self._read(readsize)
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:   File "/usr/lib64/python2.7/gzip.py", line 303, in _read
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:     self._read_gzip_header()
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:   File "/usr/lib64/python2.7/gzip.py", line 197, in _read_gzip_header
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]:     raise IOError, 'Not a gzipped file'
Feb 21 16:17:40 repochecker osrt-pkglistgen[26851]: IOError: Not a gzipped file
Feb 21 16:17:40 repochecker systemd[1]: osrt-pkglistgen@openSUSE:Leap:15.0.service: Main process exited, code=exited, status=1/FAILURE
Feb 21 16:17:40 repochecker systemd[1]: osrt-pkglistgen@openSUSE:Leap:15.0.service: Unit entered failed state.
Feb 21 16:17:40 repochecker systemd[1]: osrt-pkglistgen@openSUSE:Leap:15.0.service: Failed with result 'exit-code'.
```

Maybe gets a mirror that transparently decompresses gzip?

**Comment by jberry-suse** [comment]
Yeah, I saw that a couple times while developing. I guess I'll have to run it on a loop now and again to see what's up.

**Comment by jberry-suse** [comment]
Added `--debug` flag to `osrt-pkglistgen@.service` on `tortuga`. Should include http details as to the mirror and such.

**Comment by jberry-suse** [comment]
Haven't seen it yet.

**Comment by lnussel** [comment]
first thing I had on screen today :)

Feb 22 10:40:45 repochecker osrt-pkglistgen[17650]: DEBUG:urllib3.connectionpool:http://ftp.funet.fi:80 "GET /pub/mirrors/ftp.opensuse.com/pub/opensuse/update/leap/42.3/oss/repodata/cf8a48c7862ff6b64c129e1bf762443061c5969572502d82d0c36f5611f32023-primary.xml.gz HTTP/1.1" 200 11982104

**Comment by lnussel** [comment]
maybe w should circumvent mirrors and go for internal systems

**Comment by jberry-suse** [comment]
That file is no longer available, but the current one is not gzip'd. Just text/xml.

http://ftp.funet.fi/pub/mirrors/ftp.opensuse.com/pub/opensuse/update/leap/42.3/oss/repodata/

Is there a simple way to force no mirror or convenient place from where to grab the data? Realistically I would assume this is an issue for users unless zypper gracefully ignores the lack of gzip. As such should probably poke the mirror.

**Comment by jberry-suse** [comment]
With #1439 this will now show up as:

```
Exception: checksums do not match 4e78daf8df74c2d9a477fd501d86a77d3bdd4d6f2aed1a6be8c07ca751df7d01 != 0e36336180ca13c98ced19d4e8b07f74b7647be1075c8fae615167349cccf8c3
```

Not really an improvement, but short of placing after trying to parse as gzip...

**Comment by coolo** [comment]
if you want to enforce no mirror usage, replace download.opensuse.org with downloadcontent.opensuse.org

**Comment by jberry-suse** [comment]
Indeed. Which is what #1418 does, but thus does not go as far back and depends on having proper archive.

**Comment by coolo** [comment]
Will work on this archive
