### ISSUE TITLE
Missing snapshot-changes directory for new versions - should it be auto-created?

### ISSUE THREAD

**Issue by okurz** [openSUSE/openSUSE-release-tools#1597]
## Observation

Trying to sync and trigger openSUSE Leap 15.1 reports an error about a missing 15.1 directory within /var/lib/snapshot-changes/opensuse/

```
geekotest@ariel:/opt/openqa-scripts> env RSYNC_PASSWORD=*** ./rsync.pl --verbose --add-existing 15.1
geekotest@ariel:/opt/openqa-scripts> env RSYNC_PASSWORD=ALWAYS_TESTED ./rsync.pl --verbose --dry --add-existing 15.1
Syncing '15.1'
reposync rsync://openqa@obs-backend.publish.opensuse.org/opensuse-internal/build//openSUSE:Leap:15.1/images/local/*product:openSUSE-ftp-ftp-x86_64/openSUSE-*-Media2/
  -> openSUSE-15.1-oss-i586-x86_64-Snapshot269.2-debuginfo
build '269.5' of repo 'openSUSE-15.1-x86_64-Build269.5' doesn't match iso with build '269.2'
reposync rsync://openqa@obs-backend.publish.opensuse.org/opensuse-internal/build//openSUSE:Leap:15.1/images/local/*product:openSUSE-ftp-ftp-x86_64/openSUSE-*-Media1/
  -> openSUSE-15.1-oss-i586-x86_64-Snapshot269.2
build '269.5' of repo 'openSUSE-15.1-x86_64-Build269.5' doesn't match iso with build '269.2'
reposync rsync://openqa@obs-backend.publish.opensuse.org/opensuse-internal/build//openSUSE:Leap:15.1/images/local/*product:openSUSE-Addon-NonOss-ftp-ftp-x86_64/openSUSE-*-Media1/
  -> openSUSE-15.1-non-oss-i586-x86_64-Snapshot269.2
build '269.5' of repo 'openSUSE-Leap-15.1-Addon-NonOss-FTP-x86_64-Build269.5' doesn't match iso with build '269.2'
  rsync://openqa@obs-backend.publish.opensuse.org/opensuse-internal/build//openSUSE:Leap:15.1:ToTest/images/local/000product:openSUSE-cd-mini-x86_64/openSUSE-Leap-15.1-NET-x86_64-Build269.2-Media.iso
  -> openSUSE-Leap-15.1-NET-x86_64-Build269.2-Media.iso...
  rsync://openqa@obs-backend.publish.opensuse.org/opensuse-internal/build//openSUSE:Leap:15.1:ToTest/images/local/000product:openSUSE-dvd5-dvd-x86_64/openSUSE-Leap-15.1-DVD-x86_64-Build269.2-Media.iso
  -> openSUSE-Leap-15.1-DVD-x86_64-Build269.2-Media.iso...
[
  "/opt/openqa-scripts/factory-package-news.py",
  "save",
  "--dir",
  "/var/lib/snapshot-changes/opensuse/15.1",
  "--snapshot",
  269.2,
  "openSUSE-Leap-15.1-DVD-x86_64-Build269.2-Media.iso",
]
Traceback (most recent call last):
  File "/opt/openqa-scripts/factory-package-news.py", line 286, in <module>
    sys.exit( app.main() )
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 261, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 284, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 422, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 1123, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/opt/openqa-scripts/factory-package-news.py", line 164, in do_save
    raise Exception("%s must be a directory"%opts.dir)
Exception: /var/lib/snapshot-changes/opensuse/15.1 must be a directory
```

## Steps to reproduce

* Login to o3
* As geekotest call the command as mentioned above
* Observe the error message

This can also be reproduced by calling just

```
/opt/openqa-scripts/factory-package-news.py save --dir /var/lib/snapshot-changes/opensuse/15.1 --snapshot 269.2 openSUSE-Leap-15.1-DVD-x86_64-Build269.2-Media.iso
```

**Comment by jberry-suse** [comment]
It certainly could, but presumably is not.

**Comment by lnussel** [comment]
https://progress.opensuse.org/issues/37141 has the instructions to create the directory. you closed the issue as done :)

**Comment by okurz** [comment]
ok, sorry. Have missed the instructions
