### ISSUE TITLE
Pika update to 1.0 broke openQA monitor

### ISSUE THREAD

**Issue by coolo** [openSUSE/openSUSE-release-tools#1972]
```
INFO:__main__:Connecting to opensuse
Traceback (most recent call last):
  File "./scripts/gocd/rabbit-openqa.py", line 267, in <module>
    l.run(runtime=3600)
  File "/godata/pipelines/openSUSE.openQA/scripts/PubSubConsumer.py", line 330, in run
    self._connection = self.connect()
  File "/godata/pipelines/openSUSE.openQA/scripts/PubSubConsumer.py", line 70, in connect
    parameters = pika.ConnectionParameters(server, 5671, '/', credentials, ssl=True, socket_timeout=10)
  File "/usr/lib/python2.7/site-packages/pika/connection.py", line 658, in __init__
    raise TypeError('unexpected kwargs: %r' % (kwargs,))
TypeError: unexpected kwargs: {'ssl': True}
[script-executor] Script completed with exit code: 1.
```

**Comment by coolo** [comment]
https://pika.readthedocs.io/en/stable/version_history.html

**Comment by coolo** [comment]
this was fixed
