### ISSUE TITLE
python3 osc-plugin-staging: unstage crashes on RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by lethliel** [openSUSE/openSUSE-release-tools#2029]
originally reported by @lkocman 

Hello,

This could perhaps be duplicate of Bug #1130541, but it crashes in different piece of code.

I'm using the last osc available in packagehub for SP1 Beta

osc-plugin-staging-20190308.7f2195f-bp151.1.1.noarch

$ iosc staging -p SUSE:SLE-12-SP5:GA unselect 187461
Unselecting "187461" from "SUSE:SLE-12-SP5:GA:Staging:A"
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/lib/osc-plugins/osc-staging.py", line 521, in do_staging
    UnselectCommand(api).perform(args[1:], opts.cleanup)
  File "/usr/lib/osc-plugins/osclib/unselect_command.py", line 66, in perform
    self.api.update_status_or_deactivate(prj, 'unselect')
  File "/usr/lib/osc-plugins/osclib/stagingapi.py", line 1468, in update_status_or_deactivate
    self.staging_deactivate(project)
  File "/usr/lib/osc-plugins/osclib/stagingapi.py", line 1742, in staging_deactivate
    CommentAPI(self.apiurl).delete_from(project_name=project)
  File "/usr/lib/osc-plugins/osclib/comments.py", line 239, in delete_from
    comments = self.delete_children(comments)
  File "/usr/lib/osc-plugins/osclib/comments.py", line 218, in delete_children
    for comment in comments.values():
RuntimeError: dictionary changed size during iteration

**Comment by jberry-suse** [comment]
How not to migrate to python3...suddenly. :/

**Comment by coolo** [comment]
this is already fixed - and we have one other issue as reminder to update the packagehub package, so closing this
