### ISSUE TITLE
Accepting staged delete requests fails

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2055]
While running osc staging accept, the command fails on handling delete requests and 'virtually accepting them':

> Accepting staging review for avogadro and started handling of virtual accept process
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/dimstar_suse/.osc-plugins/osc-staging.py", line 509, in do_staging
    if cmd.perform(api.prj_from_letter(prj), opts.force):
  File "/home/dimstar_suse/.osc-plugins/osclib/accept_command.py", line 144, in perform
    self.virtually_accept_delete(req['id'], req['package'])
  File "/home/dimstar_suse/.osc-plugins/osclib/accept_command.py", line 105, in virtually_accept_delete
    meta = ''.join(meta)
TypeError: sequence item 0: expected str instance, bytes found

**Comment by coolo** [comment]
`decode_it` is your friend
