### ISSUE TITLE
update repos fails for ppc

### ISSUE THREAD

**Issue by coolo** [openSUSE/openSUSE-release-tools#2165]
```
Traceback (most recent call last):
  File "./pkglistgen.py", line 8, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 261, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 284, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 422, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 1123, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/godata/pipelines/Update.Repos.Factory/pkglistgen/cli.py", line 41, in do_handle_update_repos
    return update_project(conf.config['apiurl'], project)
  File "/godata/pipelines/Update.Repos.Factory/pkglistgen/update_repo_handler.py", line 210, in update_project
    dump_solv(solv_file, opts['url'])
  File "/godata/pipelines/Update.Repos.Factory/pkglistgen/update_repo_handler.py", line 140, in dump_solv
    if not parse_repomd(repo, baseurl) and not parse_susetags(repo, baseurl):
  File "/godata/pipelines/Update.Repos.Factory/pkglistgen/update_repo_handler.py", line 131, in parse_susetags
    repo.add_susetags(f, defvendorid, None, solv.Repo.REPO_NO_INTERNALIZE|solv.Repo.SUSETAGS_RECORD_SHARES)
  File "/usr/lib64/python3.7/site-packages/solv.py", line 1426, in add_susetags
    return _solv.Repo_add_susetags(self, fp, defvendor, language, flags)
TypeError: in method 'Repo_add_susetags', argument 2 of type 'FILE *'
[script-executor] Script completed with exit code: 1.

**Comment by coolo** [comment]
fixed by changing repos
