### ISSUE TITLE
TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by lkocman** [openSUSE/openSUSE-release-tools#2206]
Hello

I'm getting following exception TypeError: Unicode-objects must be encoded before hashing on most of staging operations select/accept. This is also happening with builds equal or newer than osc-plugin-staging-20190829.72c1e9b4-1.1.noarch. osc-plugin-staging-20190828* doesn't seem to suffer from this.

lkocman@linux-i0y4:~/Workspace/openSUSE-release-tools> git show HEAD
commit 783a06742387cf95a9765eebb8754c4924125146 (HEAD -> master, upstream/master)
Merge: b269bf48 66c91247
Author: Jimmy Berry <jberry@suse.com>
Date:   Thu Sep 5 14:14:31 2019 -0500

    Merge pull request #2201 from jberry-suse/osclib-comments-command-find-allow-seperators
    
    osclib/comments: command_find(): allow seperators after user.

lkocman@linux-i0y4:~/Workspace/openSUSE-release-tools> 

lkocman@linux-i0y4:~/Workspace/openSUSE-release-tools> iosc-staging-s12 select c cjose
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/home/lkocman/Workspace/osc/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/home/lkocman/Workspace/osc/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/home/lkocman/Workspace/osc/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/home/lkocman/Workspace/osc/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/home/lkocman/Workspace/osc/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/lkocman/.osc-plugins/osc-staging.py", line 573, in do_staging
    splitter.strategy_do('requests', requests=requests)
  File "/home/lkocman/Workspace/openSUSE-release-tools/osclib/request_splitter.py", line 347, in strategy_do
    self.strategy_set(name, **kwargs)
  File "/home/lkocman/Workspace/openSUSE-release-tools/osclib/request_splitter.py", line 51, in strategy_set
    self.strategy = cls(**kwargs)
  File "/home/lkocman/Workspace/openSUSE-release-tools/osclib/request_splitter.py", line 389, in __init__
    self.key += '_' + hashlib.sha1(str(kwargs)).hexdigest()[:7]
TypeError: Unicode-objects must be encoded before hashing

**Comment by jberry-suse** [comment]
Based on the stack trace there and looking at the command your supplied it is clear you meant `C` and not `c`. As for the other problem I'll look into it, but should have no relationship to that commit.

As a side note, one can utilize `.osc/project` in a directory to set the working project for both `osc`, `osc staging` and `osc origin` to avoid the need for project specific aliases.
