### ISSUE TITLE
factory-package-news: Fails on Tumbleweed

### ISSUE THREAD

**Issue by ggardet** [openSUSE/openSUSE-release-tools#2216]
The 1st issue I have with `save` command, is I need to replace `/suse/noarch` by `/noarch` (same for x86_64, aarch64, etc.).

Then it fails (for both x86_64 and aarch64 ISO) on `save` command with the following error:
```
data['changelogtext'][0] = - updated to 4.12
  see /usr/share/doc/packages/perl-Cpanel-JSON-XS/Changes
  4.12 2019-06-11 (rurban)
  - Make encoder independent on Math::BigInt version (#140 by Pali)
  - Rethrow error from eval_sv and eval_pv() (#138, #139 by Pali),
    e.g. when Math::BigInt/BigFloat fails.
  - Fix encoding Inf and NaN from PV and NV slots to JSON_TYPE_INT
    (#137 by Pali)
  - Fix memory corruption in sv_to_ivuv() function (#136 by Pali)
  - Add new method ->require_types (#135 by Pali)
  - Fix typed json encoder conversion from scalar's PV and NV slot to
    JSON_TYPE_INT (#133, #134 by Pali)
  - Fix inconsistency with warnings in typed json encoder (#131 by Pali)
  - Fix Perl 5.8.0 support (#130 by Pali)
  - Fixed minor pod typo (#129 by sheeit)
  - Document invalid recursive callbacks or overloads (#128)
Traceback (most recent call last):
  File "../factory-package-news.py", line 285, in <module>
    sys.exit( app.main() )
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 261, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 284, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 422, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 1123, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "../factory-package-news.py", line 163, in do_save
    pickle.dump([data_version, self.readChangeLogs(dirs)], f)
  File "../factory-package-news.py", line 130, in readChangeLogs
    _getdata(h)
  File "../factory-package-news.py", line 100, in _getdata
    data['changelogtext'][t] = str(txt, 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 344: invalid continuation byte
```

If I skip `perl-Cpanel-JSON-XS` package, no error are shown.

Diff error was due to local changes.
<s>With `diff` command, I get the following error:
```
Traceback (most recent call last):
  File "../factory-package-news.py", line 286, in <module>
    sys.exit( app.main() )
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 261, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 284, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 422, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 1123, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "../factory-package-news.py", line 235, in do_diff
    t1 = v1changelogs[srpm1]['changelogtime'][0]
KeyError: 'openSUSE-release-20190830-184.1.src.rpm'
```
</s>

**Comment by ggardet** [comment]
Same kind of error with `inspect 20190907 openSUSE-release`:
```
{'name': 'openSUSE-release',
 'release': '190.1',
 'sourcerpm': 'openSUSE-release-20190907-190.1.src.rpm',
 'version': '20190907'}
Traceback (most recent call last):
  File "../factory-package-news.py", line 286, in <module>
    sys.exit( app.main() )
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 261, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 284, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 422, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 1123, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "../factory-package-news.py", line 184, in do_inspect
    pprint(changelogs[pkgs[package]['sourcerpm']])
KeyError: 'openSUSE-release-20190907-190.1.src.rpm'
```

**Comment by ggardet** [comment]
For `perl-Cpanel-JSON-XS`, it seems that `perl-Cpanel-JSON-XS.changes` is not a valid UTF-8 file: https://build.opensuse.org/package/view_file/openSUSE:Factory:ARM/perl-Cpanel-JSON-XS/perl-Cpanel-JSON-XS.changes?expand=1

Not sure why production is not affected, though.
