### ISSUE TITLE
osrt-pkglistgen exception

### ISSUE THREAD

**Issue by dsamx** [openSUSE/openSUSE-release-tools#2238]
I want to use pkglistgen to create the product specification for a project in OBS.
I created a 000package-groups package which is based on https://build.opensuse.org/package/show/openSUSE:Leap:15.1/000package-groups and executed
osrt-pkglistgen update_and_solve -p myproject --only-release-packages
which resulted in the following exception:
Traceback (most recent call last):
  File "/usr/bin/osrt-pkglistgen", line 8, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.6/site-packages/cmdln.py", line 261, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/cmdln.py", line 284, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/cmdln.py", line 422, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/cmdln.py", line 1123, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/share/openSUSE-release-tools/pkglistgen/cli.py", line 77, in do_update_and_solve
    main_repo = target_config['main-repo']
KeyError: 'main-repo'

I have no idea what to do, due to the lack of documentation and the uncommented code.

**Comment by coolo** [comment]
you need to copy the OSRT:Config attribute from 15.1
