### ISSUE TITLE
TTM.Leap_15.2_PowerPC is broken

### ISSUE THREAD

**Issue by coolo** [openSUSE/openSUSE-release-tools#2313]
CC @michelmno 

```
scripts/totest-manager.py -A https://api.opensuse.org --debug run openSUSE:Leap:15.2:PowerPC
[script-executor] -------------------------
[script-executor] Script Type: bash
[script-executor] Script written into '/go/pipelines/TTM.Leap_15.2_PowerPC/10fd9061-20e4-428d-add6-cbd3a2373fd5.sh'.
INFO:ttm.manager:job opensuse-15.2-DVD-ppc64le-Build-extra_tests_in_textmode@ppc64le failed, see https://openqa.opensuse.org/tests/1075767
INFO:ttm.manager:job opensuse-15.2-DVD-ppc64le-Build-RAID0@ppc64le failed, see https://openqa.opensuse.org/tests/1075769
INFO:ttm.manager:job opensuse-15.2-DVD-ppc64le-Build-create_hdd_kde@ppc64le failed, see https://openqa.opensuse.org/tests/1075770
INFO:ttm.manager:job opensuse-15.2-DVD-ppc64le-Build-extra_tests_on_kde@ppc64le failed, see https://openqa.opensuse.org/tests/1075771
INFO:ttm.manager:job opensuse-15.2-DVD-ppc64le-Build-lvm@ppc64le failed, see https://openqa.opensuse.org/tests/1075777
INFO:ttm.manager:job opensuse-15.2-DVD-ppc64le-Build-yast2_ncurses@ppc64le failed, see https://openqa.opensuse.org/tests/1075781
INFO:ttm.manager:job opensuse-15.2-DVD-ppc64le-Build-extra_tests_on_gnome@ppc64le failed, see https://openqa.opensuse.org/tests/1075782
INFO:ttm.manager:current_snapshot 13.1: failed
DEBUG:ttm.manager:current_qa_version 13.1
DEBUG:ttm.manager:No ttm_amqp_url configured in oscrc - skipping amqp event emission
Traceback (most recent call last):
  File "scripts/totest-manager.py", line 8, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 261, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 284, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 422, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/cmdln.py", line 1123, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/godata/pipelines/TTM.Leap_15.2_PowerPC/scripts/ttm/cli.py", line 67, in do_run
    ToTestReleaser(self.tool).release(project)
  File "/godata/pipelines/TTM.Leap_15.2_PowerPC/scripts/ttm/releaser.py", line 31, in release
    new_snapshot = self.version_from_project()
  File "/godata/pipelines/TTM.Leap_15.2_PowerPC/scripts/ttm/releaser.py", line 74, in version_from_project
    return self.iso_build_version(self.project.name, self.project.main_products[0])
  File "/godata/pipelines/TTM.Leap_15.2_PowerPC/scripts/ttm/manager.py", line 69, in iso_build_version
    raise NotFoundException("can't find %s iso version" % project)
ttm.manager.NotFoundException: can't find openSUSE:Leap:15.2:PowerPC iso version
[script-executor] Script completed with exit code: 1.

**Comment by nilxam** [comment]
I think that because we reverted Leap product rename change in 000package-groups for now, and 000package-groups is broken(needs rebase) therefore there isn't a new snapshot generated.

**Comment by lkocman** [comment]
Confirmed with Max that this is no longer an issue
