### ISSUE TITLE
staging setprio: 'Staging Project "FOO" does not exist

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2353]
I just tried to bump up the prio (mainly for legal - even though nobody looks at it) for Staging G, but this results in:

> osc staging setprio G
Staging Project "G" does not exist.

from osc -d, it becomes apparent that this is stilkl using the routes through the old dashboard:

```
GET https://api.opensuse.org/staging/openSUSE:Factory/staging_projects/G?requests=1
```

(so does osc staging check)

**Comment by coolo** [comment]
this is not the old dashboard - this is just using 'G' as staging project name. Try openSUSE:Factory:Staging:G instead

**Comment by DimStar77** [comment]
meh - too much to type :)

And fails differently:

```
~> osc staging setprio openSUSE:Factory:Staging:G
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.7/site-packages/osc/babysitter.py", line 62, in run
    return prg.main(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/dimstar_suse/.osc-plugins/osc-staging.py", line 592, in do_staging
    PrioCommand(api).perform(stagings, priority)
  File "/home/dimstar_suse/.osc-plugins/osclib/prio_command.py", line 55, in perform
    if not info['selected_requests']:
  File "src/lxml/etree.pyx", line 1158, in lxml.etree._Element.__getitem__
TypeError: 'str' object cannot be interpreted as an integer
```

**Comment by coolo** [comment]
*that*'s the old api :)
