### ISSUE TITLE
accept with deletes exception

### ISSUE THREAD

**Issue by lnussel** [openSUSE/openSUSE-release-tools#2364]
The project was green...
```
$ osc staging -p openSUSE:Leap:15.2 accept B
delete links to packages pending deletion...
delete openSUSE:Leap:15.2:Rings:1-MinimalX/python-pep8
triggering staging accepts...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 62, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/lnussel_factory/.osc-plugins/osc-staging.py", line 426, in do_staging
    cmd.accept_all(args[1:], opts.force, not opts.no_cleanup)
  File "/home/lnussel_factory/.osc-plugins/osclib/accept_command.py", line 112, in accept_all
    http_POST(u)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 3394, in http_POST
    def http_POST(*args, **kwargs):   return http_request('POST', *args, **kwargs)
  File "/home/lnussel_factory/.osc-plugins/osclib/cache.py", line 36, in http_request
    ret = osc.core._http_request(method, url, headers, data, file)
  File "/usr/lib/python3.6/site-packages/osc/core.py", line 3382, in http_request
    fd = urlopen(req, data=data)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
Server returned an error: HTTP Error 400: Bad Request
Staging project is not in state acceptable.

```

**Comment by coolo** [comment]
I already considered running the staging accept always with force after we checked in the client that it's acceptable. WDYT?

**Comment by DimStar77** [comment]
> I already considered running the staging accept always with force after we checked in the client that it's acceptable. WDYT?

Would match what I did so far with my accept_green_stagins script: find all green ones then force accept them
