### ISSUE TITLE
openqabot broken after last XML module change

### ISSUE THREAD

**Issue by msmeissn** [openSUSE/openSUSE-release-tools#2723]
the last change of the xml module used, broke the openqabot.

DEBUG: Called test_job with: {'project': 'openSUSE:Maintenance:17401', 'id': '17401', 'channels': ['openSUSE:Backports:SLE-15-SP3:Update']}
DEBUG: openSUSE:Leap:15.2:Update -- product in apimap
DEBUG: Pmap: {'version': '15.2', 'flavor': 'DVD-Incidents', 'distri': 'opensuse'} Posts: []
DEBUG: openSUSE:Leap:15.3:Update -- product in apimap
DEBUG: Pmap: {'version': '15.3', 'flavor': 'DVD-Incidents', 'distri': 'opensuse'} Posts: []
DEBUG: openSUSE:Backports:SLE-15-SP3:Update -- product in apimap
Traceback (most recent call last):
  File "./openqa-maintenance.py", line 9, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.8/site-packages/cmdln.py", line 261, in main
    return self.cmd(args)
  File "/usr/lib/python3.8/site-packages/cmdln.py", line 284, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.8/site-packages/cmdln.py", line 422, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.8/site-packages/cmdln.py", line 1123, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/godata/pipelines/openSUSE.QA.Maint/ReviewBot.py", line 930, in do_review
    return self.runner(work, opts.interval)
  File "/godata/pipelines/openSUSE.QA.Maint/ReviewBot.py", line 954, in runner
    return workfunc()
  File "/godata/pipelines/openSUSE.QA.Maint/ReviewBot.py", line 928, in work
    return self.checker.check_requests()
  File "/godata/pipelines/openSUSE.QA.Maint/oqamaint/openqabot.py", line 69, in check_requests
    self.check_opensuse_incidents()
  File "/godata/pipelines/openSUSE.QA.Maint/oqamaint/openqabot.py", line 527, in check_opensuse_incidents
    self.test_job({'project': build, 'id': incident_id, 'channels': list(tgt_prjs)})
  File "/godata/pipelines/openSUSE.QA.Maint/oqamaint/openqabot.py", line 558, in test_job
    openqa_posts += self.check_product(mesh_job, prod)
  File "/godata/pipelines/openSUSE.QA.Maint/oqamaint/openqabot.py", line 478, in check_product
    posts += self.check_product_arch(job, product_prefix, pmap, None)
  File "/godata/pipelines/openSUSE.QA.Maint/oqamaint/openqabot.py", line 452, in check_product_arch
    for j in update.settings(
  File "/godata/pipelines/openSUSE.QA.Maint/oqamaint/opensuse.py", line 56, in settings
    settings = super(openSUSEUpdate, self).settings(src_prj, dst_prj)
  File "/godata/pipelines/openSUSE.QA.Maint/oqamaint/update.py", line 49, in settings
    patch_id = self.patch_id(repo)
  File "/godata/pipelines/openSUSE.QA.Maint/oqamaint/update.py", line 79, in patch_id
    root = ET.fromstring(repomd.text)
  File "src/lxml/etree.pyx", line 3252, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1907, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
[script-executor] Script completed with exit code: 1.

**Comment by nilxam** [comment]
Don't know what has been changed in lxml, but it looks like now it works with encoded string, not decoded string, use `repomd.text.encode('utf-8')` or `repomd.content` worked.

**Comment by msmeissn** [comment]
see https://github.com/openSUSE/openSUSE-release-tools/pull/2724 from @coolo , can you review and merge?
