### ISSUE TITLE
zstd missing in pkglistgen container on botmaster

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2725]
Fallout from https://github.com/openSUSE/openSUSE-release-tools/pull/2720

pkglistgen fails to calculate the product content, as zstd is missing inside the containers

```
Traceback (most recent call last):
  File "/godata/pipelines/Pkglistgen.openSUSE_Factory/pkglistgen/cli.py", line 98, in solve_project
    if self.tool.update_and_solve_target(api, target_project, target_config, main_repo,
  File "/godata/pipelines/Pkglistgen.openSUSE_Factory/pkglistgen/tool.py", line 689, in update_and_solve_target
    self.create_weakremovers(project, target_config, oldrepos_dir, output=open(weakremovers_file, 'w'))
  File "/godata/pipelines/Pkglistgen.openSUSE_Factory/pkglistgen/tool.py", line 417, in create_weakremovers
    oldsysrepo = file_utils.add_susetags(pool, oldrepo)
  File "/godata/pipelines/Pkglistgen.openSUSE_Factory/pkglistgen/file_utils.py", line 75, in add_susetags
    subprocess.call(['zstd', '-cd', file], stdout=f.fileno())
  File "/usr/lib64/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'zstd'
[script-executor] Script completed with exit code: 1.
```

**Comment by coolo** [comment]
fixed
