### ISSUE TITLE
Staging accept fails for TW - bugowner check

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2799]
```
Accepting all acceptable projects
Traceback (most recent call last):                                             File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.6/site-packages/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 347, in main        return self.cmd(args)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 370, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 504, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python3.6/site-packages/osc/cmdln.py", line 1235, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/dimstar_suse/.osc-plugins/osc-staging.py", line 428, in do_staging
    cmd.accept_all(args[1:], opts.force, not opts.no_cleanup)
  File "/home/dimstar_suse/.osc-plugins/osclib/accept_command.py", line 114, in accept_all
    self.check_request_for_bugowner(bugowners_to_request, request.get('package'), request.get('id'))
  File "/home/dimstar_suse/.osc-plugins/osclib/accept_command.py", line 71, in check_request_for_bugowner
    description = root.find('description').text
AttributeError: 'NoneType' object has no attribute 'text'
```

Reverted my machine to commit 3e495a4f1e40 to perform the check-in today

**Comment by coolo** [comment]
hmm, a request without description? It would have been nice to know which request that was

**Comment by DimStar77** [comment]
> hmm, a request without description? It would have been nice to know which request that was

That's very common - https://build.opensuse.org/request/show/967525 had no subscription (should be ready for accept today)

I can collect more debug this evening - will try to open for more utile in then just accept and run

**Comment by coolo** [comment]
I see... ```r.description(description) unless description.nil?```
