### ISSUE TITLE
sourcechecker crashes on git managed packages

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/openSUSE-release-tools#2820]
pending SR: https://build.opensuse.org/request/show/984629

sourcechecker bot crashes with:

```
[I] target package does not exist openSUSE:Factory/obs-service-download_assets
Traceback (most recent call last):
  File "/godata/pipelines/openSUSE.Source.Check/ReviewBot.py", line 198, in check_requests
    good = self.check_one_request(req)
  File "/godata/pipelines/openSUSE.Source.Check/ReviewBot.py", line 442, in check_one_request
    ret = func(req, a)
  File "/godata/pipelines/openSUSE.Source.Check/ReviewBot.py", line 534, in check_action_submit
    return self.check_source_submission(a.src_project, a.src_package, a.src_rev, a.tgt_project, a.tgt_package)
  File "/godata/pipelines/openSUSE.Source.Check/./check_source.py", line 197, in check_source_submission
    CheckSource.checkout_package(self.apiurl, source_project, source_package, revision=source_revision,
  File "/godata/pipelines/openSUSE.Source.Check/./check_source.py", line 419, in checkout_package
    result = osc.core.checkout_package(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/osc/core.py", line 5184, in checkout_package
    raise oscerr.OscIOError(None, 'Install the obs-scm-bridge package to work on packages managed in scm (git)!')
osc.oscerr.OscIOError
[I] 984629 ignored
[script-executor] Script completed with exit code: 1.
```

The package metadata has, in the devel project:
```
<package name="obs-service-download_assets" project="openSUSE:Tools">
  <title/>
  <description/>
  <scmsync>https://github.com/openSUSE/obs-service-download_assets.git</scmsync>
</package>
```

(but this is not the first package we have which is git based - python-orangebox also does that already)

**Comment by coolo** [comment]
Newly deployed - no longer crashing! :) 
https://build.opensuse.org/request/show/984629
