### ISSUE TITLE
typing hints break on SLES 15 SP3

### ISSUE THREAD

**Issue by msmeissn** [openSUSE/openSUSE-release-tools#2880]
$ osc diff
Traceback (most recent call last):
  File "/usr/bin/osc", line 43, in <module>
    osccli = commandline.Osc()
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 92, in __init__
    self._load_plugins()
  File "/usr/lib/python3.6/site-packages/osc/commandline.py", line 9583, in _load_plugins
    mod = imp.load_source(modname, os.path.join(plugin_dir, extfile))
  File "/usr/lib64/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/osc-plugins/osc-staging.py", line 17, in <module>
    from osclib.accept_command import AcceptCommand
  File "/usr/lib/osc-plugins/osclib/accept_command.py", line 14, in <module>
    from osclib.pkglistgen_comments import PkglistComments
  File "/usr/lib/osc-plugins/osclib/pkglistgen_comments.py", line 48, in <module>
    class PkglistComments:
  File "/usr/lib/osc-plugins/osclib/pkglistgen_comments.py", line 168, in PkglistComments
    def is_approved(self, comment, comments: dict) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

I think it might not be python3.6 compatible syntax?

**Comment by coolo** [comment]
Cherry pick https://github.com/openSUSE/openSUSE-release-tools/pull/2878/commits/20123a357a77b63531e22579e8c84a0172ca7d47

**Comment by skriesch** [comment]
This behaviour is also on openSUSE Leap 15.3.

**Comment by coolo** [comment]
Of course, every platform with python 3.6

**Comment by coolo** [comment]
@SchoolGuy's fixup was merged now
