### ISSUE TITLE
setprio: enhance to allow non-important priorities

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/openSUSE-release-tools#971]
iosc staging setprio -p SUSE:SLE-12-SP3:GA C important

returns (after doing its work)

Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/fcrozat/.osc-plugins/osc-staging.py", line 594, in do_staging
    PrioCommand(api).perform(args[1:])
  File "/home/fcrozat/.osc-plugins/osclib/prio_command.py", line 63, in perform
    info = self.api.project_status(project, aggregate)
  File "/home/fcrozat/.osc-plugins/osclib/memoize.py", line 185, in _fn
    value = fn(*args, **kwargs)
  File "/home/fcrozat/.osc-plugins/osclib/stagingapi.py", line 940, in project_status
    return json.load(self.retried_GET(url))
  File "/usr/lib64/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by jberry-suse** [comment]
Presumably this was intermittent? It seems the obs_factory plugin on OBS end times out now and again.

**Comment by fcrozat** [comment]
I have it every time on IBS (just tested again)

**Comment by coolo** [comment]
because setprio only takes stagings - and important is none

**Comment by coolo** [comment]
--help is your friend

**Comment by fcrozat** [comment]
so, setprio always set to important ? This isn't really explained in --help. Feel free to close bug report.

**Comment by DimStar77** [comment]
OTOH, it would be nice if setprio _could_ be used to lower prios of a staging / request too (e.g. lowering the haskell stuff in some cases)

**Comment by jberry-suse** [comment]
I made the priority configurable and added proper help.
